#!/usr/bin/env python3
"""
Regenerate store-derived wiki schema extracts from the live ChromaDB store.

This generates `data/wiki/schema/persona_catalog.json` — a complete, always-current index of
every persona in the store with post counts, post-type breakdown, tier, and the most-mentioned
tools/topics. It is purely mechanical (derived from the store), so it can be rebuilt any time.

It does NOT touch `personas.json`, which is a small **hand-curated** profile of the core
founders (priority rank, channels, key patterns, ingestion status) — curation a mechanical dump
would destroy. The catalog complements it: curated depth for the few, generated breadth for all.

Usage:
  python3 scripts/build_wiki_schema.py            # rebuild persona_catalog.json
  python3 scripts/build_wiki_schema.py --dry-run  # print summary, write nothing
  python3 scripts/build_wiki_schema.py --top-terms 8

Tip: export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 to skip HF Hub HTTP checks.
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

SCHEMA_DIR = Path("data/wiki/schema")
CATALOG_PATH = SCHEMA_DIR / "persona_catalog.json"

# Personas that are not external thought leaders (internal memory, aggregates) — flagged so
# downstream consumers can exclude them from community/trend aggregation.
NON_LEADER_PERSONAS = {"aaa_project"}


def _split_csv(value: str) -> list[str]:
    return [v.strip() for v in (value or "").split(",") if v.strip()]


def build_catalog(top_terms: int = 6) -> dict:
    from src.pipeline.linkedin_persona_store import LinkedInPersonaStore  # noqa: PLC0415

    store = LinkedInPersonaStore()
    store.initialize()
    data = store._collection.get(include=["metadatas"])
    metas = data["metadatas"]

    by_persona: dict[str, dict] = {}
    for m in metas:
        pid = m.get("persona_id", "unknown")
        p = by_persona.setdefault(pid, {
            "persona_id": pid,
            "author": m.get("author", ""),
            "post_count": 0,
            "post_types": Counter(),
            "tools": Counter(),
            "topics": Counter(),
            "tier": m.get("source_tier") or "external",
        })
        p["post_count"] += 1
        p["post_types"][m.get("post_type", "unknown")] += 1
        for t in _split_csv(m.get("mentioned_tools", "")):
            p["tools"][t] += 1
        for t in _split_csv(m.get("topics", "")):
            p["topics"][t] += 1
        if not p["author"] and m.get("author"):
            p["author"] = m["author"]

    personas = []
    for p in by_persona.values():
        personas.append({
            "persona_id": p["persona_id"],
            "author": p["author"],
            "post_count": p["post_count"],
            "post_types": dict(p["post_types"].most_common()),
            "top_tools": [t for t, _ in p["tools"].most_common(top_terms)],
            "top_topics": [t for t, _ in p["topics"].most_common(top_terms)],
            "tier": p["tier"],
            "is_thought_leader": p["persona_id"] not in NON_LEADER_PERSONAS,
        })
    personas.sort(key=lambda x: -x["post_count"])

    return {
        "schema_version": "1.0",
        "description": (
            "Store-derived catalog of every persona in the linkedin_reactions collection. "
            "Generated by scripts/build_wiki_schema.py — do not hand-edit. Curated core "
            "profiles live in personas.json."
        ),
        "total_personas": len(personas),
        "total_posts": sum(p["post_count"] for p in personas),
        "personas": personas,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate store-derived wiki schema extracts")
    parser.add_argument("--dry-run", action="store_true", help="Print summary, write nothing")
    parser.add_argument("--top-terms", type=int, default=6, help="Top N tools/topics per persona")
    args = parser.parse_args()

    catalog = build_catalog(top_terms=args.top_terms)
    print(f"Persona catalog: {catalog['total_personas']} personas, "
          f"{catalog['total_posts']} posts.")
    print("Top 5 by post count:")
    for p in catalog["personas"][:5]:
        leader = "" if p["is_thought_leader"] else "  (internal, not a leader)"
        print(f"  {p['post_count']:>3}  {p['author'] or p['persona_id']}{leader}")

    if args.dry_run:
        print("\nDRY RUN — nothing written.")
        return

    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")
    print(f"\nWritten → {CATALOG_PATH}")


if __name__ == "__main__":
    main()
